### ISSUE TITLE
Report an Issue/Bug/error

### ISSUE THREAD

**Issue by sandeshlavshetty** [sandeshlavshetty/I.N.S.P.I.R.E#4]
**Expected Format**
Example :-
{
**Bug Description**:
When submitting a poll, the confirmation ticket does not generate.

**Steps to Reproduce**:
1. Log in to the app.
2. Go to the polling page.
3. Submit your preferred class timing.
4. Wait for the confirmation ticket to generate (this step fails).

**Expected Result**:
A confirmation ticket with the selected time should appear.

**Actual Result**:
No ticket appears, and an error message is shown.

**Error Message (if any)**:
"Ticket generation failed."

**Browser/Device**:
Google Chrome, Windows 10

**Supported images or screenshots**
}

**Comment by sumedh210** [comment]
There is an error in time display in the token. The time displayed is of the server and not of the device using the webapp.

**Comment by sandeshlavshetty** [comment]
> There is an error in time display in the token. The time displayed is of the server and not of the device using the webapp.

This is an issue of dynamic server routing , we will update as soon it is fixed.
(Note:- Its our request to provide bug in presented format)

**Comment by sandeshlavshetty** [comment]
> There is an error in time display in the token. The time displayed is of the server and not of the device using the webapp.

**Comment by sandeshlavshetty** [comment]
> There is an error in time display in the token. The time displayed is of the server and not of the device using the webapp.

@sumedh210 
Time issue has been resolved check our Feature Announcements for the updated view of tickets

Thanks for reporting this Bug 🐞
@sandeshlavshetty
