### ISSUE TITLE
🚀 Feature Request

### ISSUE THREAD

**Issue by sandeshlavshetty** [sandeshlavshetty/I.N.S.P.I.R.E#5]
#### 📋 Description
*A clear and concise description of what the feature is.*

> _Example_: I would like to add a **polling feature** to the web application so users can participate in various polls and view results in real-time.

---

#### 🎯 Problem or Motivation
*Explain why this feature is needed and how it would benefit the project.*

> _Example_: Currently, there is no way to gather user feedback within the app. Adding a polling system would increase user engagement and allow for quick, real-time surveys.

---

#### 💡 Proposed Solution(Optional)
*Describe your proposed solution in detail. Include steps, technologies, and any design aspects.*

> _Example_: I propose adding a new endpoint in the backend to handle poll creation and a front-end component for voting. Using a database to store results and WebSockets for real-time updates.

---

#### 📚 Alternatives Considered
*If there are any alternative solutions or existing features, describe them here.*

> _Example_: We could use third-party polling services like Google Forms, but they would not offer real-time updates or full control over the user experience.

---

#### 🔗 Additional Context
*Provide any additional context, screenshots, or links to relevant documentation or existing code.*

> _Example_: Mockup of the polling interface: [Link to image/mockup]
> API documentation for real-time communication: [Link to WebSocket docs]

---

**Comment by Akshith-Vemisetti** [comment]
---

### Request for INSPIRE Tickets

**Description:**

I would like to request the following INSPIRE tickets along with their associated BT IDs and usernames. This information will help streamline our tracking and management process.

**Requirements:**

- Provide a list of INSPIRE tickets.
- Include the corresponding BT ID for each ticket.
- Include the username associated with each ticket.

**Example Format:**

| Ticket ID | BT ID     | Username         |
|-----------|-----------|------------------|
| 001       | BT12345   | user_one         |
| 002       | BT67890   | user_two         |

**Additional Notes:**

- Please ensure that the information is up to date.
- If possible, include any relevant comments or status updates related to the tickets.

Thank you for your assistance!

---

**Comment by sandeshlavshetty** [comment]
> ### Request for INSPIRE Tickets
> **Description:**
> 
> I would like to request the following INSPIRE tickets along with their associated BT IDs and usernames. This information will help streamline our tracking and management process.
> 
> **Requirements:**
> 
> * Provide a list of INSPIRE tickets.
> * Include the corresponding BT ID for each ticket.
> * Include the username associated with each ticket.
> 
> **Example Format:**
> 
> Ticket ID	BT ID	Username
> 001	BT12345	user_one
> 002	BT67890	user_two
> **Additional Notes:**
> 
> * Please ensure that the information is up to date.
> * If possible, include any relevant comments or status updates related to the tickets.
> 
> Thank you for your assistance!

---

Thank you for submitting this feature request for **INSPIRE Tickets**. We understand the importance of having a streamlined tracking system, and providing ticket IDs along with their associated BT IDs and usernames is a valuable addition.

We will work on implementing this feature and ensuring that the ticket information is up-to-date, including any relevant comments or status updates for each ticket. 

Our team will keep you informed as we progress with this feature and will notify you once it’s available for use. We appreciate your patience and your continued support for the INSPIRE project!

Feel free to reach out if you have any additional requests or questions.

---

**Comment by sandeshlavshetty** [comment]
---

# Feature Update for INSPIRE Tickets Request

Hello @Akshith-Vemisetti,

Thank you for your feature request regarding the INSPIRE tickets. I’m happy to inform you that the requested functionality has been completed and deployed successfully. Below is an example of how INSPIRE tokens will now appear:

### Mobile View:  
![image](https://github.com/user-attachments/assets/98684772-a7fa-4f7f-ad23-0c96b7c22a62)

### PC Screen View:  
![Screenshot 2024-09-19 111828](https://github.com/user-attachments/assets/0a26577f-220e-42c9-9a7b-1ad913f561ca)

Please feel free to review and provide any feedback or additional comments!

Best regards,  
@sandeshlavshetty

---

**Comment by sandeshlavshetty** [comment]
---

# Feature Update for INSPIRE Tickets Request

Hello @Akshith-Vemisetti,

Thank you for your feature request regarding the INSPIRE tickets. I’m happy to inform you that the requested functionality has been completed and deployed successfully. Below is an example of how INSPIRE tokens will now appear:

### Mobile View:  
![image](https://github.com/user-attachments/assets/98684772-a7fa-4f7f-ad23-0c96b7c22a62)

### PC Screen View:  
![Screenshot 2024-09-19 111828](https://github.com/user-attachments/assets/0a26577f-220e-42c9-9a7b-1ad913f561ca)

Please feel free to review and provide any feedback or additional comments!

Best regards,  
@sandeshlavshetty

---
